C_FILES= cscd240Lab19.c fileUtil.c words.c linkedList.c listUtils.c
H_FILES= fileUtil.h myUtils.h words.h linkedList.h listUtils.h
O_FILES= myUtils.o
 
lab19:	${C_FILES} ${H_FILES}
	gcc -g -o lab19 ${C_FILES} ${O_FILES}
