C_FILES= cscd240Lab18.c fileUtil.c lab18.c stock.c linkedList.c myUtils.c
H_FILES= lab18.h fileUtil.h myUtils.h stock.h linkedList.h
 
lab18:	${C_FILES} ${H_FILES}
	gcc -g -o lab18 ${C_FILES} ${O_FILES}
